Using watsonx api instead of http request
IBM/ibmdotcom-tutorials pull request #16
Opened 2024-10-25 15:22 UTC by AnnaGutowska

2024-10-25 15:35 UTC, Erika-Russi requested changes

2024-10-25 15:35 UTC, Erika-Russi commented on generative-ai/multimodal-ai.ipynb
> +    "%pip install -U \"ibm_watsonx_ai>=1.1.14\" | tail -n 1"
```suggestion
    "%pip install -U \"ibm_watsonx_ai>=1.1.14\" | tail -n 1"
    "%pip install python-dotenv | tail -n 1"
```
need to add this package

2024-10-25 16:11 UTC, Erika-Russi approved these changes

2024-10-29 14:15 UTC, aspleenic approved these changes
lgtm

2024-10-29 14:15 UTC, merged